"""Boîte à outils modulaire de SudMedia.

Ce module regroupe l'ensemble des utilitaires partagés, organisés en sous-packages
thématiques :
- console : configuration du terminal et encodage UTF-8/VT100
- filesystem : chemins, exclusions, scans récursifs, écritures atomiques et quarantaine
- hashing : empreintes binaires (SHA256), perceptuelles (dHash) et index de similarité (BK-tree)
- image : configuration Pillow, formats, métadonnées et redimensionnement
- progress : barre de progression universelle et formatage temporel
- metrics : calculs de tailles, analyse de qualité et bilans d'opération
- folder_archive : compression, décompression et vérification d'archives ZIP / TAR.XZ
- duplicate : analyse et détection de doublons exacts et similaires
- ocr : extraction de texte, intégration Tesseract OCR et PDF
"""

from __future__ import annotations

# Sous-packages thématiques
from . import console, duplicate, filesystem, folder_archive, hashing, image, metrics, ocr, progress
from .folder_archive import (
    BUFFER_SIZE,
    CompressionBackendError,
    ExtractionBackendError,
    Toolchain,
    compress_tar_xz_python,
    compress_zip_python,
    describe_backend,
    detect_sevenzip,
    detect_toolchain,
    detect_xz,
    execute_compression,
    execute_extraction,
    extract_tar_xz_python,
    extract_zip_python,
    full_verify_xz,
    full_verify_zip,
    parse_threads,
    quick_verify_xz,
    quick_verify_zip,
    verify_archive,
)
from .console import configure_console_output
from .duplicate import (
    DuplicateGroup,
    DuplicateReport,
    FileCandidate,
    quarantine_duplicates,
    scan_duplicates,
)
from .filesystem import (
    DEFAULT_IGNORED_DIRECTORIES,
    EXCLUDE_PATTERNS,
    IGNORED_DIRECTORY_NAMES,
    FileEntry,
    QuarantineResult,
    ScannedEntry,
    archive_base_name,
    atomic_write_json,
    atomic_write_text,
    clean_input_path,
    collect_files,
    collect_target_files,
    detect_archive_format,
    make_staging_folder,
    paths_overlap,
    quarantine_files,
    remove_output_from_entries,
    reserve_output_path,
    resolve_archive_output_path,
    resolve_extraction_paths,
    safe_member_path,
    scan_folder,
    unique_available_path,
    unique_path,
    walk_filtered,
)
from .hashing import (
    HammingIndex,
    content_hash,
    difference_hash,
    hamming_distance,
    hash_file,
)
from .image import (
    IMAGE_EXTENSIONS,
    IMAGE_OUTPUT_FORMATS,
    MEDIA_EXTENSIONS,
    RESIZE_METHODS,
    VIDEO_EXTENSIONS,
    configure_pillow,
    get_original_image_quality,
    image_save_options,
    prepare_image_for_format,
    prepare_image_for_quality,
    resize_image,
)
from .metrics import (
    ProcessingStats,
    QualityAnalysis,
    SizeAnalysis,
    analyze_quality,
    analyze_size_change,
    format_size,
    normalize_quality,
    print_processing_summary,
    print_quality_analysis,
)
from .progress import (
    Progress,
    ProgressReader,
    format_duration,
    format_size_short,
    render_progress,
)
from .ocr import (
    OCR_EXTENSIONS,
    OCRBackend,
    OCRDocument,
    OCRPage,
    OCRResult,
    TesseractBackend,
    extract_document,
    find_tesseract,
    process_documents,
    render_document,
    write_document,
)

__all__ = [
    "BUFFER_SIZE",
    "CompressionBackendError",
    "DEFAULT_IGNORED_DIRECTORIES",
    "DuplicateGroup",
    "DuplicateReport",
    "EXCLUDE_PATTERNS",
    "ExtractionBackendError",
    "FileCandidate",
    "FileEntry",
    "HammingIndex",
    "IGNORED_DIRECTORY_NAMES",
    "IMAGE_EXTENSIONS",
    "IMAGE_OUTPUT_FORMATS",
    "MEDIA_EXTENSIONS",
    "OCRDocument",
    "OCRPage",
    "OCRResult",
    "OCR_EXTENSIONS",
    "OCRBackend",
    "ProcessingStats",
    "Progress",
    "ProgressReader",
    "QualityAnalysis",
    "QuarantineResult",
    "RESIZE_METHODS",
    "ScannedEntry",
    "SizeAnalysis",
    "TesseractBackend",
    "Toolchain",
    "VIDEO_EXTENSIONS",
    "analyze_quality",
    "analyze_size_change",
    "folder_archive",
    "archive_base_name",
    "atomic_write_json",
    "atomic_write_text",
    "clean_input_path",
    "collect_files",
    "collect_target_files",
    "compress_tar_xz_python",
    "compress_zip_python",
    "configure_console_output",
    "configure_pillow",
    "console",
    "content_hash",
    "describe_backend",
    "detect_archive_format",
    "detect_sevenzip",
    "detect_toolchain",
    "detect_xz",
    "difference_hash",
    "duplicate",
    "execute_compression",
    "execute_extraction",
    "extract_document",
    "extract_tar_xz_python",
    "extract_zip_python",
    "filesystem",
    "find_tesseract",
    "format_duration",
    "format_size",
    "format_size_short",
    "full_verify_xz",
    "full_verify_zip",
    "get_original_image_quality",
    "hamming_distance",
    "hash_file",
    "hashing",
    "image",
    "image_save_options",
    "make_staging_folder",
    "metrics",
    "normalize_quality",
    "ocr",
    "parse_threads",
    "paths_overlap",
    "prepare_image_for_format",
    "prepare_image_for_quality",
    "print_processing_summary",
    "print_quality_analysis",
    "process_documents",
    "progress",
    "quarantine_duplicates",
    "quarantine_files",
    "quick_verify_xz",
    "quick_verify_zip",
    "remove_output_from_entries",
    "render_document",
    "render_progress",
    "reserve_output_path",
    "resize_image",
    "resolve_archive_output_path",
    "resolve_extraction_paths",
    "safe_member_path",
    "scan_duplicates",
    "scan_folder",
    "select_backend",
    "unique_available_path",
    "unique_path",
    "verify_archive",
    "walk_filtered",
    "write_document",
]
